name: Code checks  # имя

on:  # на какие события срабатывает pipeline
  push: # срабатывает на push...
    branches: [ master ]  # ... в бранч master
  pull_request: # срабатывает на pull request...
    branches: [ master ]  # ... в бранч master

jobs:  # что будет выполнено, когда произойдет какое-либо событие, указанное выше
  build:
    runs-on: ubuntu-latest  # версия OS
    strategy:  # блок для выполнения тестов на нескольких версиях питона
      matrix:  # Параллельный запуск job'ов
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2  # создается образ репозитория, в котором будут выполнены дальнейшие шаги
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2  # устанавливается питон
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps  # Это блок-ран, блок последовательных команд, установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests  # Запускаем тесты
        run: python -m pytest -s -v tests/test_func.py
      - name: Run Alternative Tests  # Запускаем альтернативные тесты
        run: python -m pytest -s -v tests_alternative/test_func.py
